export const SET_LOADING = "SET_LOADING";
export const SET_POOL_DATA = "SET_POOL_DATA";

export const SET_ACTIVE_LINK_ID = "SET_ACTIVE_LINK_ID";
export const SET_LIST_DATA = "SET_LIST_DATA";
export const SET_DATE_DIAPASON = "SET_DATE_DIAPASON";
export const SET_CHART_DATA = "SET_CHART_DATA";
export const SET_SWITCH_POSITION = "SET_SWITCH_POSITION";
export const SET_VOLUME_TO_LIST = "SET_VOLUME_TO_LIST";
export const SET_EXCHANGE_DATA = "SET_EXCHANGE_DATA";

export const SET_PRICE_DATA = "SET_PRICE_DATA";

export const SET_BALANCER_PRICE = "SET_BALANCER_PRICE";
export const SET_UNISWAP_PRICE = "SET_UNISWAP_PRICE";

export const SET_IS_SUCCESS = "SET_IS_SUCCESS";
export const SET_IS_ERROR = "SET_IS_ERROR";
export const SKIP_STATUS = "SKIP_STATUS";

